filebeat.inputs:
- type: log
  enabled: true
  json.keys_under_root: true
  json.add_error_key: true
#  json.message_key: message_key
  paths:
    - /var/datainsights-logs/*/info.json

#output.logstash:
#  enable: false
#  hosts: ["datainsights-logstash:5044"]

output.kafka:
  enable: true
  hosts: ["192.168.10.73:9092"]
  topic: "spring_cloud_log"
  partition.round_robin:
    reachable_only: true
